function plotter_boundness
    addpath ../product_1
    close all;

    % Create figure
    figure1 = figure('InvertHardcopy','off','Color',[1 1 1], ...
        'position', [680 0 600 570]);
    set(figure1,'PaperUnits','centimeters');
    xSize = 8; ySize = 12;
    xLeft = (21-xSize)/2; yTop = (30-ySize)/2;
    %set(figure1,'PaperPosition',[xLeft yTop xSize ySize]);
    %set(figure1,'Position',[X Y xSize*50 ySize*50]);

    hold on
    %axis([-1.7 1.7 -1.7 1.7]);
%     axis([-2 2 -2 2]);
     axis([-2.5 2.5 -2.5 2.5]);
%     axis([-3.8 2.2 -3 3]);
    
    plot([-1 0], [0 -1], 'color', 'k', 'LineWidth', 3);
    plot([0 1], [1 0], 'color', 'k', 'LineWidth', 3);

    %plot([-1 0], [0 1], 'color', 'k', 'LineWidth', 3);
    %plot([0 1], [-1 0], 'color', 'k', 'LineWidth', 3);


    % Дополнительные границы
    ax=axis;
    plot(ax(1:2), [ax(4) ax(4)], 'k', 'LineWidth', 1);
    plot([ax(2) ax(2)], ax(3:4), 'k', 'LineWidth', 1);

    % Экспериментальные данные для бесконечно большого числа нейронов.
    % tau = 1.0
%     a = [ -0.83 -0.60 -0.40 -0.20 -0.1 0 ];
%     b = [  0.83  1.03  1.17  1.18  1.1 1 ];

    tau = 0.5;
    a = [ -1.08 -1.00 -0.80 -0.60 -0.40 -0.2 0 ];
    b = [  1.08  1.15  1.3   1.38  1.36  1.2 1 ];

%     tau = 0.3;
%     a = [ -1.35 -1.0  -0.80  -0.5 -0.3 0 ];
%     b = [  1.35  1.6   1.63   1.5  1.3 1 ];

    % Экспериментальные данные для бесконечно большого числа нейронов.
    % для второго типа нейронов.
%     tau = 1.0;
%     a = [ -0.66 -0.46 -0.3  0];
%     b = [  0.66  0.86  1.0  1];

%     tau = 0.5;
%     a = [ -0.83 -0.62 -0.38 -0.21 -0.17 -0.05 0];
%     b = [  0.83  1.02  1.18  1.20  1.17  1.05 1];

%     tau = 0.2;
%     a = [ -1.19 -1.09  -0.91 -0.77 -0.6 -0.49 -0.25 0];
%     b = [  1.19  1.29   1.41  1.48  1.5  1.45  1.25 1];

    
    interp(a, b, true, 'k');
    
%plot (1.5, 0.6, '*r') ;

    number = 4 ;
    N = 36;
    PI = 2*pi;
    %[r phi taus] = solver_boundness_smart(number, .5, .0001);
    phi = 0 : PI/N: PI;
    [r taus] = solver_boundness(number, tau, phi, .1);
%title(['$n = ' num2str(number) ', \tau = ' num2str(tau) '$'],'FontSize',20, 'interpreter', 'latex');
title(['$n = ' num2str(number) '$'],'FontSize',30, 'interpreter', 'latex');

%excludePoints(4) ;
    
    h = polar(phi, r);
    set(h, 'LineWidth', 3) ;
    
    % display debug data
    debug = 0;
    if debug
        str = cell(size(taus));
        if debug == 1
            for j=1:length(taus)
                str{j} = num2str(j-1);
            end
        elseif debug == 2
            for j=1:length(taus)
                str{j} = [num2str(j-1) ':' num2str(phi(j)*180/pi, 3) arr2str(taus{j}) num2str(r(j),2)];
            end
        end
        r = r+0.2;
        text(r.*cos(phi), r.*sin(phi), str);
    end
    
    grid; 

    function excludePoints (n)
        r (n) = (r(n-1) + r(n+1))/2 ;
    end
    
    % Функция интерполирует экспериментальные данные
    function interp(a, b, sim, color, titleString)
        x = a(1):.001:a(end);
        y = interp1(a, b, x, 'spline' );

        if sim
            xx = [-y(end:-1:2) x];
            yy = [-x(end:-1:2) y];
        else 
            xx = x;
            yy = y;
        end

        plot(xx, yy, color, 'LineWidth', 3);
        plot(-xx, -yy, color, 'LineWidth', 3);

        aa = [a -b(end:-1:2)];
        bb = [b -a(end:-1:2)];
        %plot(aa, bb, 'ok', xx, yy, color, 'LineWidth', 1);
        %plot(-aa, -bb, 'ok', -xx, -yy, color, 'LineWidth', 1);
        if exist('titleString', 'var') 
            title(['$n = ' num2str(titleString) ', \tau = ' num2str(tau) '$'],'FontSize',16, 'interpreter', 'latex');
        end
    end

% Autogenerated code.
% Create xlabel
xlabel({'a'}, 'FontSize',16);

% Create ylabel
ylabel({'b'}, 'FontSize',16);

% Create textbox
annotation(figure1,'textbox',...
    [0.429930957050318 0.48027939504748 0.133224346076459 0.0847826086956548],...
    'String','Stability',...
    'FontSize',16,...
    'FitBoxToText','off',...
    'LineStyle','none',...
    'EdgeColor',[1 1 1]);



% Create textbox
annotation(figure1,'textbox',...
    [0.19904017857143 0.254566473988439 0.133459821428571 0.0708202587393341],...
    'String',{'Instability'},...
    'FontSize',16,...
    'FitBoxToText','off',...
    'LineStyle','none',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.654821428571429 0.783236994219653 0.133459821428571 0.0708202587393341],...
    'String',{'Instability'},...
    'FontSize',16,...
    'FitBoxToText','off',...
    'LineStyle','none',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.24802956628661 0.739096207470175 0.133459821428571 0.0708202587393342],...
    'Interpreter','latex',...
    'String',{['$n = ' num2str(number) '$']},...
    'FontSize',16,...
    'FitBoxToText','off',...
    'LineStyle','none',...
    'EdgeColor',[1 1 1]);

% Create textbox
annotation(figure1,'textbox',...
    [0.334445841716969 0.60174631098984 0.133459821428571 0.0708202587393342],...
    'Interpreter','latex',...
    'String',{'$n = \infty$'},...
    'FontSize',16,...
    'FitBoxToText','off',...
    'LineStyle','none',...
    'EdgeColor',[1 1 1]);


end

